# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ov7670_hdmi.xdc

# Block Designs: bd/ov7670_capture/ov7670_capture.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov7670_capture || ORIG_REF_NAME==ov7670_capture} -quiet] -quiet

# IP: bd/ov7670_capture/ip/ov7670_capture_processing_system7_0_0/ov7670_capture_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov7670_capture_processing_system7_0_0 || ORIG_REF_NAME==ov7670_capture_processing_system7_0_0} -quiet] -quiet

# IP: bd/ov7670_capture/ip/ov7670_capture_v_tc_0_0/ov7670_capture_v_tc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov7670_capture_v_tc_0_0 || ORIG_REF_NAME==ov7670_capture_v_tc_0_0} -quiet] -quiet

# IP: bd/ov7670_capture/ip/ov7670_capture_v_axi4s_vid_out_0_0/ov7670_capture_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov7670_capture_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==ov7670_capture_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/ov7670_capture/ip/ov7670_capture_rgb2dvi_0_0/ov7670_capture_rgb2dvi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov7670_capture_rgb2dvi_0_0 || ORIG_REF_NAME==ov7670_capture_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/ov7670_capture/ip/ov7670_capture_clk_wiz_0_0/ov7670_capture_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov7670_capture_clk_wiz_0_0 || ORIG_REF_NAME==ov7670_capture_clk_wiz_0_0} -quiet] -quiet

# IP: bd/ov7670_capture/ip/ov7670_capture_ps7_0_axi_periph_0/ov7670_capture_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov7670_capture_ps7_0_axi_periph_0 || ORIG_REF_NAME==ov7670_capture_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ov7670_capture/ip/ov7670_capture_rst_ps7_0_100M_0/ov7670_capture_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov7670_capture_rst_ps7_0_100M_0 || ORIG_REF_NAME==ov7670_capture_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/ov7670_capture/ip/ov7670_capture_xbar_0/ov7670_capture_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov7670_capture_xbar_0 || ORIG_REF_NAME==ov7670_capture_xbar_0} -quiet] -quiet

# IP: bd/ov7670_capture/ip/ov7670_capture_axi_mem_intercon_0/ov7670_capture_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov7670_capture_axi_mem_intercon_0 || ORIG_REF_NAME==ov7670_capture_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/ov7670_capture/ip/ov7670_capture_axi_vdma_0_3/ov7670_capture_axi_vdma_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov7670_capture_axi_vdma_0_3 || ORIG_REF_NAME==ov7670_capture_axi_vdma_0_3} -quiet] -quiet

# IP: bd/ov7670_capture/ip/ov7670_capture_ov7670_driver_0_0/ov7670_capture_ov7670_driver_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov7670_capture_ov7670_driver_0_0 || ORIG_REF_NAME==ov7670_capture_ov7670_driver_0_0} -quiet] -quiet

# IP: bd/ov7670_capture/ip/ov7670_capture_axis_subset_converter_0_0/ov7670_capture_axis_subset_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov7670_capture_axis_subset_converter_0_0 || ORIG_REF_NAME==ov7670_capture_axis_subset_converter_0_0} -quiet] -quiet

# IP: bd/ov7670_capture/ip/ov7670_capture_auto_pc_0/ov7670_capture_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov7670_capture_auto_pc_0 || ORIG_REF_NAME==ov7670_capture_auto_pc_0} -quiet] -quiet

# IP: bd/ov7670_capture/ip/ov7670_capture_auto_pc_1/ov7670_capture_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov7670_capture_auto_pc_1 || ORIG_REF_NAME==ov7670_capture_auto_pc_1} -quiet] -quiet

# XDC: d:/FPGA/FPGA/digital_logic/ov7670_VGA/ov7670_VGA/ov7670_VGA.gen/sources_1/bd/ov7670_capture/ov7670_capture_ooc.xdc
