######################################################################
#
# File name : hdmi_colorbar_top_wave.do
# Created on: Tue Apr 25 15:59:32 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
