######################################################################
#
# File name : tb_hdmi_colorbar_top_compile.do
# Created on: Sun Jun 25 14:17:43 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech64_10.5\\win64\\vlib modelsim_lib/work
C:\\modeltech64_10.5\\win64\\vlib modelsim_lib/msim

C:\\modeltech64_10.5\\win64\\vlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.5\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.5\\win64\\vlog  -incr -work xil_defaultlib  "+incdir+../../../../hdmi_color.gen/sources_1/ip/clk_wiz_0" \
"../../../../hdmi_color.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_clk_wiz.v" \
"../../../../hdmi_color.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.v" \
"../../../../../rtl/asyn_rst_syn.v" \
"../../../../../rtl/dvi_encoder.v" \
"../../../../../rtl/dvi_transmitter_top.v" \
"../../../../../rtl/hdmi_colorbar_top.v" \
"../../../../../rtl/serializer_10_to_1.v" \
"../../../../../rtl/video_display.v" \
"../../../../../rtl/video_driver.v" \
"../../../../../sim/tb_hdmi_colorbar_top.v" \


# compile glbl module
C:\\modeltech64_10.5\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

