######################################################################
#
# File name : tb_hdmi_colorbar_top_wave.do
# Created on: Sun Jun 25 14:17:44 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
