######################################################################
#
# File name : tb_hdmi_colorbar_simulate.do
# Created on: Tue Jun 06 15:50:15 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L xpm -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_hdmi_colorbar xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_hdmi_colorbar_wave.do}

view wave
view structure
view signals

do {tb_hdmi_colorbar.udo}

run 1000ns
