######################################################################
#
# File name : tb_hdmi_colorbar_wave.do
# Created on: Tue Apr 25 16:09:47 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
