######################################################################
#
# File name : tb_serializer.udo
# Created on: Mon May 08 14:44:49 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
