######################################################################
#
# File name : tb_serializer_compile.do
# Created on: Mon May 08 14:52:19 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xpm
vlib modelsim_lib/msim/xil_defaultlib

vmap xpm modelsim_lib/msim/xpm
vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog  -incr -sv -work xpm  "+incdir+../../../../hdmi_color.gen/sources_1/ip/clk_wiz_0" \
"D:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \

vcom  -93 -work xpm  \
"D:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd" \

vlog  -incr -work xil_defaultlib  "+incdir+../../../../hdmi_color.gen/sources_1/ip/clk_wiz_0" \
"../../../../../rtl/serializer_10_to_1.v" \
"../../../../hdmi_color.srcs/sim_1/new/tb_serializer.v" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

