######################################################################
#
# File name : tb_serializer_wave.do
# Created on: Mon May 08 14:44:49 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
